### ISSUE TITLE
Was Working well now almost twice a day it crashes

### ISSUE THREAD

**Issue by Slepperpon** [pdlove/homebridge-smartthings#103]
TypeError: Cannot read property 'error' of undefined
    at /usr/local/lib/node_modules/homebridge-smartthings/index.js:70:30
    at /usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:93:13
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:46:27)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by pdlove** [comment]
@Slepperpon Are you good with the latest update?

**Comment by Slepperpon** [comment]
Have not updated yet

Adam Hoffman
Aamco Transmission
Lee's Summit



On Feb 17, 2017, at 4:09 PM, pdlove <notifications@github.com<mailto:notifications@github.com>> wrote:


@Slepperpon<https://github.com/Slepperpon> Are you good with the latest update?

**Comment by Slepperpon** [comment]
Every thing is working on my end thank you

________________________________
