### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by Maxmudjon** [pdlove/homebridge-smartthings#177]
e","Signal Strength","Water Sensor"]
[4/26/2017, 4:04:52 PM] [SmartThings] Initializing platform accessory 'п▓я┘п╬пЄп                                                                                                 Ґп╟я▐ п■п╡п╣я─я▄'...
[4/26/2017, 4:04:52 PM] [SmartThings] Initializing platform accessory 'п п╩п╟пЄп                                                                                                 ╬п╡п╨п╟'...
[4/26/2017, 4:04:52 PM] [SmartThings] Initializing platform accessory 'п║п©п╟п╩я                                                                                                 ▄пҐя▐'...
[4/26/2017, 4:04:52 PM] [SmartThings] Initializing platform accessory 'п░пҐя▌я┌п                                                                                                 ╟'...
[4/26/2017, 4:04:52 PM] [SmartThings] Initializing platform accessory 'п■п╣я┌я│п                                                                                                 ╨п╟я▐'...
[4/26/2017, 4:04:53 PM] [SmartThings] Initializing platform accessory 'п я┐я┘пҐя                                                                                                 ▐'...
[4/26/2017, 4:04:53 PM] [SmartThings] Initializing platform accessory 'п≈п╟п╩'..                                                                                                 .
[4/26/2017, 4:04:53 PM] [SmartThings] Initializing platform accessory 'п п╩п╟пЄп                                                                                                 ╬п╡п╟я▐'...
[4/26/2017, 4:04:53 PM] [SmartThings] Initializing platform accessory 'п⌡п╬пЄпІп                                                                                                 ╦я▐'...
[4/26/2017, 4:04:53 PM] [SmartThings] Initializing platform accessory 'п÷я─п╦я┘п                                                                                                 ╬пІп╨п╟'...
[4/26/2017, 4:04:53 PM] [SmartThings] Initializing platform accessory 'п║п╣пҐя│п                                                                                                 ╬я─ п÷я─п╬я┌п╣я┤п╨п╦'...
[4/26/2017, 4:04:53 PM] [SmartThings] Initializing platform accessory 'п║п╣я─пЁп                                                                                                 ╣п╧'...
[4/26/2017, 4:04:53 PM] [SmartThings] Initializing platform accessory 'п║п©п╟п╩я                                                                                                 ▄пҐя▐'...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:                                                                                                 228
      throw new Error("Cannot add a bridged Accessory with the same UUID as anot                                                                                                 her bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Acce                                                                                                 ssory: 0a4956f7-0571-45e3-b97c-59dfcf5cc40d
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebri                                                                                                 dge/node_modules/hap-nodejs/lib/Accessory.js:228:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:                                                                                                 367:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/o                                                                                                 nce.js:16:19
    at /usr/local/lib/node_modules/homebridge-smartthings/index.js:121:4
    at /usr/local/lib/node_modules/homebridge-smartthings/index.js:98:5
    at /usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:                                                                                                 94:29
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-smart                                                                                                 things/lib/smartthingsapi.js:45:29)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)

**Comment by Maxmudjon** [comment]
all right))
