### ISSUE TITLE
[SmartThings] Error received type undefined - undefined

### ISSUE THREAD

**Issue by mrquatsch** [pdlove/homebridge-smartthings#184]
I can't seem to load anything using the home bridge-smartthings plugin. I can confirm that I have fetched the latest GitHub master branch for the homebridge.smarthings plugin and I remove the legacy plugins as well.

**homebridge.smartthings plugin version**
`npm -v homebridge-smartthings
3.10.10`

**NodeJS version**
`nodejs -v
v0.10.29`

**And I'm running this on a raspberry pi 2 with the latest jesse build.**
`uname -a
Linux raspberrypi 4.4.50+ #970 Mon Feb 20 19:12:50 GMT 2017 armv6l GNU/Linux`

**Here's a snippet of my logs.** 
```
[6/4/2017, 3:20:45 AM] [SmartThings] Error received type undefined - undefined
[6/4/2017, 3:20:45 AM] [SmartThings] Unknown Capabilities: []
[6/4/2017, 3:20:45 AM] [SmartThings] Direct Connect Is Listening On 192.168.3.192:8000
```

**And here's the entire log**
```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[6/4/2017, 3:20:22 AM] Loaded plugin: homebridge-chamberlain
[6/4/2017, 3:20:22 AM] Registering accessory 'homebridge-chamberlain.Chamberlain'
[6/4/2017, 3:20:22 AM] ---
[6/4/2017, 3:20:31 AM] Loaded plugin: homebridge-nest
[6/4/2017, 3:20:31 AM] Registering platform 'homebridge-nest.Nest'
[6/4/2017, 3:20:31 AM] ---
[6/4/2017, 3:20:43 AM] Loaded plugin: homebridge-smartthings
[6/4/2017, 3:20:43 AM] Registering platform 'homebridge-smartthings.SmartThings'
[6/4/2017, 3:20:43 AM] ---
[6/4/2017, 3:20:43 AM] Loaded config.json with 1 accessories and 2 platforms.
[6/4/2017, 3:20:43 AM] ---
[6/4/2017, 3:20:43 AM] Loading 2 platforms...
[6/4/2017, 3:20:43 AM] [Nest] Initializing Nest platform...
[6/4/2017, 3:20:43 AM] [Nest] Fetching Nest devices.
[6/4/2017, 3:20:43 AM] [SmartThings] Initializing homebridge-smartthings.SmartThings platform...
[6/4/2017, 3:20:43 AM] [SmartThings] Fetching Smart Things devices.
[6/4/2017, 3:20:44 AM] Loading 1 accessories...
[6/4/2017, 3:20:44 AM] [GarageDoor] Initializing Chamberlain accessory...
[6/4/2017, 3:20:45 AM] [SmartThings] Error received type undefined - undefined
[6/4/2017, 3:20:45 AM] [SmartThings] Unknown Capabilities: []
[6/4/2017, 3:20:45 AM] [SmartThings] Direct Connect Is Listening On 192.168.3.192:8000
[6/4/2017, 3:20:48 AM] [Nest] Software version for Dining Room Thermostat is: 5.6.2-3
[6/4/2017, 3:20:48 AM] [Nest] Temperature unit for Dining Room Thermostat is: Fahrenheit
[6/4/2017, 3:20:48 AM] [Nest] Current temperature for Dining Room Thermostat is: 71 F
[6/4/2017, 3:20:48 AM] [Nest] Current heating for Dining Room Thermostat is: Cooling
[6/4/2017, 3:20:48 AM] [Nest] Current humidity for Dining Room Thermostat is: 40%
[6/4/2017, 3:20:48 AM] [Nest] Target temperature for Dining Room Thermostat is: 70 F
[6/4/2017, 3:20:48 AM] [Nest] Target heating for Dining Room Thermostat is: Heating/Cooling
[6/4/2017, 3:20:48 AM] [Nest] Away for Dining Room Thermostat is: 0
[6/4/2017, 3:20:48 AM] [Nest] Software version for Downstairs Nest Protect is: 3.1.2rc1
[6/4/2017, 3:20:48 AM] [Nest] Software version for Entryway Camera is: 214-610038
[6/4/2017, 3:20:48 AM] [Nest] Away for Entryway Camera is: 0
[6/4/2017, 3:20:48 AM] [Nest] Software version for Backyard Camera is: 214-610038
[6/4/2017, 3:20:48 AM] [Nest] Away for Backyard Camera is: 0
[6/4/2017, 3:20:48 AM] [Nest] Initializing platform accessory 'Dining Room Thermostat'...
[6/4/2017, 3:20:48 AM] [Nest] Initializing platform accessory 'Downstairs Nest Protect'...
[6/4/2017, 3:20:48 AM] [Nest] Initializing platform accessory 'Entryway Camera'...
[6/4/2017, 3:20:48 AM] [Nest] Initializing platform accessory 'Backyard Camera'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[6/4/2017, 3:20:49 AM] Homebridge is running on port 51826.
```

**And here's my config. It's worth stating that I feel I'm not properly enabling debug logging here.**
```
{
    "bridge": {
        "name": "HomebridgePi",
        "username": "XXXXXXXXXX",
        "port": 51826,
        "pin": "031-45-154",
	 "scripts": {
		 "start": "DEBUG=* homebridge -D"
  	}
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
       {
            "accessory": "Chamberlain",
            "name": "GarageDoor",
            "username": "XXXXXXXXXX,
            "password": "XXXXXXXXXX"
        }
    ],

    "platforms": [
        {
            "platform": "Nest",
            "name": "Nest",
            "displayName": "Nest",
            "token" : "XXXXXXXXXX",
            "clientId": "XXXXXXXXXX",
            "clientSecret": "XXXXXXXXXX",
            "code": "XXXXXXXXXX",
            "username" : "XXXXXXXXX",
            "password" : "XXXXXXXXXX"
        },
        {
            "platform": "homebridge-smartthings.SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "XXXXXXXXXXX",
            "access_token": "XXXXXXXXXX",
            "polling_seconds": 3600,
            "update_method": "direct",
            "direct_port": 8000,
            "api_seconds": 30
        }
    ]
}
```

Any idea what I'm missing here? I'm really just trying to get my zwave smoke detector into HomeKit; which I can already see within the smart things app.

**UPDATE:** After playing around with it for about an hour and without changing anything, I know see the following in my logs. I believe this might simply be cropping up from the multiple home bridge restarts and specifically, being rate-limited from Smartthings, so I think the above is still my problem - below is just a red herring.
```*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[6/4/2017, 3:26:07 AM] Loaded plugin: homebridge-chamberlain
[6/4/2017, 3:26:07 AM] Registering accessory 'homebridge-chamberlain.Chamberlain'
[6/4/2017, 3:26:07 AM] ---
[6/4/2017, 3:26:16 AM] Loaded plugin: homebridge-nest
[6/4/2017, 3:26:16 AM] Registering platform 'homebridge-nest.Nest'
[6/4/2017, 3:26:16 AM] ---
[6/4/2017, 3:26:28 AM] Loaded plugin: homebridge-smartthings
[6/4/2017, 3:26:28 AM] Registering platform 'homebridge-smartthings.SmartThings'
[6/4/2017, 3:26:28 AM] ---
[6/4/2017, 3:26:28 AM] Loaded config.json with 1 accessories and 2 platforms.
[6/4/2017, 3:26:28 AM] ---
[6/4/2017, 3:26:28 AM] Loading 2 platforms...
[6/4/2017, 3:26:28 AM] [Nest] Initializing Nest platform...
[6/4/2017, 3:26:28 AM] [Nest] Fetching Nest devices.
[6/4/2017, 3:26:28 AM] [SmartThings] Initializing homebridge-smartthings.SmartThings platform...
[6/4/2017, 3:26:28 AM] [SmartThings] Fetching Smart Things devices.
[6/4/2017, 3:26:29 AM] Loading 1 accessories...
[6/4/2017, 3:26:29 AM] [GarageDoor] Initializing Chamberlain accessory...
[6/4/2017, 3:26:33 AM] [Nest] Software version for Dining Room Thermostat is: 5.6.2-3
[6/4/2017, 3:26:33 AM] [Nest] Temperature unit for Dining Room Thermostat is: Fahrenheit
[6/4/2017, 3:26:33 AM] [Nest] Current temperature for Dining Room Thermostat is: 71 F
[6/4/2017, 3:26:33 AM] [Nest] Current heating for Dining Room Thermostat is: Cooling
[6/4/2017, 3:26:33 AM] [Nest] Current humidity for Dining Room Thermostat is: 40%
[6/4/2017, 3:26:34 AM] [Nest] Target temperature for Dining Room Thermostat is: 70 F
[6/4/2017, 3:26:34 AM] [Nest] Target heating for Dining Room Thermostat is: Heating/Cooling
[6/4/2017, 3:26:34 AM] [Nest] Away for Dining Room Thermostat is: 0
[6/4/2017, 3:26:34 AM] [Nest] Software version for Downstairs Nest Protect is: 3.1.2rc1
[6/4/2017, 3:26:34 AM] [Nest] Software version for Entryway Camera is: 214-610038
[6/4/2017, 3:26:34 AM] [Nest] Away for Entryway Camera is: 0
[6/4/2017, 3:26:34 AM] [Nest] Software version for Backyard Camera is: 214-610038
[6/4/2017, 3:26:34 AM] [Nest] Away for Backyard Camera is: 0
[6/4/2017, 3:26:34 AM] [Nest] Initializing platform accessory 'Dining Room Thermostat'...
[6/4/2017, 3:26:34 AM] [Nest] Initializing platform accessory 'Downstairs Nest Protect'...
[6/4/2017, 3:26:34 AM] [Nest] Initializing platform accessory 'Entryway Camera'...
[6/4/2017, 3:26:34 AM] [Nest] Initializing platform accessory 'Backyard Camera'...
[6/4/2017, 3:26:34 AM] [SmartThings] Error received type undefined - undefined
[6/4/2017, 3:26:34 AM] [SmartThings] Unknown Capabilities: []
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventedHTTPServer.listen (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:509:16)
    at Server._publish (/opt/node/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/opt/node/lib/node_modules/homebridge/lib/server.js:372:14)
    at /opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /opt/node/lib/node_modules/homebridge-smartthings/index.js:121:4
    at /opt/node/lib/node_modules/homebridge-smartthings/index.js:98:5
    at /opt/node/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:94:29
    at IncomingMessage.<anonymous> (/opt/node/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:45:29)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by mrquatsch** [comment]
GAH! I missed the last character on the access_token within my config!

I'm still receiving the rate limit error, but I am seeing it find all of my smartthings devices now - including my zwave smoke alarm. 

It's always the little things. ;)

**Comment by mrquatsch** [comment]
Oh, turns out I wasn't being rate-limited. I simply didn't kill the connection on port 8000. Rebooting the pi did the trick. 

I did have to remove home bridge from HomeKit and re-add. Once paired, everything showed up.
