### ISSUE TITLE
Updated to Node 8.7.0 and now homebridge can't seem to load homebridge-smartthings

### ISSUE THREAD

**Issue by jcharr1** [pdlove/homebridge-smartthings#212]
I updated Node to v8.7.0 through Homebrew today, and now homebridge is unable to load homebridge-smartthings. Here's the error I get:

```
[10/12/2017, 2:44:42 PM] ====================
[10/12/2017, 2:44:42 PM] ERROR LOADING PLUGIN homebridge-smartthings:
[10/12/2017, 2:44:42 PM] Error: Cannot find module 'uuid'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/node_modules/pubnub/lib/core/components/config.js:9:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
[10/12/2017, 2:44:42 PM] ====================
[10/12/2017, 2:44:42 PM] No plugins found. See the README for information on installing plugins.
[10/12/2017, 2:44:42 PM] Loaded config.json with 0 accessories and 1 platforms.
[10/12/2017, 2:44:42 PM] ---
[10/12/2017, 2:44:42 PM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:128
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'homebridge-smartthings.SmartThings' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:128:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

Here's my config.json:

```
{
        "bridge": {
                "name": "Homebridge",
                "username": "BB:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },
        
        "description": "JSON API",
        "platforms": [
                {
                        "platform": "homebridge-smartthings.SmartThings",
                        "name": "SmartThings",  
                        "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
                        "app_id": "[redacted]",
                        "access_token": "[redacted]"
                }
        ]
}
```

I've tried uninstalling and reinstalling homebridge, homebridge-smartthings, and even node several times, but it didn't help. I'm using a Mac Mini running macOS 10.13 High Sierra. Thanks! :)

**Comment by Anuj79** [comment]
getting the same error 
10/13/2017, 12:27:13 AM] ERROR LOADING PLUGIN homebridge-smartthings:
[10/13/2017, 12:27:13 AM] Error: Cannot find module 'uuid'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-smartthings/node_modules/pubnub/lib/core/components/config.js:9:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[10/13/2017, 12:27:13 AM] ====================
[10/13/2017, 12:27:13 AM] Loaded plugin: homebridge-sonos
[10/13/2017, 12:27:13 AM] Registering accessory 'homebridge-sonos.Sonos'
[10/13/2017, 12:27:13 AM] ---
[10/13/2017, 12:27:13 AM] Loaded config.json with 3 accessories and 3 platforms.
[10/13/2017, 12:27:13 AM] ---
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'SmartThings' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by Anuj79** [comment]
node -v
v6.7.0
npm -v
3.10.3

these are my versions

**Comment by Wildcat1** [comment]
@pdlove seeing the same thing as others. Any ideas on how to fix ? Thanks as always

ERROR LOADING PLUGIN homebridge-smartthings:
Error: Cannot find module 'uuid'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/node_modules/pubnub/lib/core/components/config.js:9:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/node_modules/pubnub/lib/core/pubnub-common.js:13:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/node_modules/pubnub/lib/node/index.js:7:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)

**Comment by Wildcat1** [comment]
@pdlove also when I go to the Smarthings Dashboard and update from repo I see the 3 .PNG files and the readme but cannot execute those as it fails with a 500 Internal Server Error. Just wanted to point this out as well in case another issue as well. The main issue right now is the original one above as this is not allowing Homebridge-Smarthings to work. Thanks

**Comment by Wildcat1** [comment]
Lastly (my apologies) after the Errors posted above I also see this popup for the first time 'HAP Warning: Characteristic    not in required or optional characteristics for service         . Adding anyway.' Removed numbers from the spaces as was not sure what that was exposing yet

**Comment by Anuj79** [comment]
i added the npm install -g uuid to the install.sh and that fixed it.. seems like the UUID package is missing from npm default on the docker image i had..

**Comment by jcharr1** [comment]
Installing uuid fixed it for me, too. Thanks! :)

**Comment by parsamanesh** [comment]
how do you install uuid?

**Comment by malonecentral** [comment]
From Anuj79 above: npm install -g uuid

**Comment by h00pak** [comment]
I tried npm install -g uuid and didn't get anywhere. I still get
Error: The requested platform 'SmartThings' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
