### ISSUE TITLE
Homebridge will not start up

### ISSUE THREAD

**Issue by shrowner** [pdlove/homebridge-smartthings#224]
pi@raspberrypi:~/.homebridge $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-12-7 17:30:08] Loaded plugin: homebridge-smartthings
[2017-12-7 17:30:09] Registering platform 'homebridge-smartthings.SmartThings'
[2017-12-7 17:30:09] ---
/usr/lib/node_modules/homebridge/lib/server.js:212
  var username = config.bridge.username;
                               ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:212:32)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)

**Comment by shrowner** [comment]
I was a dummy.  Didn't have the base config:

{
        "bridge": {
                "name": "Homebridge",
                "username": "BB:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },
        
        "description": "JSON API",
        "platforms": [
                {
                        "platform": "homebridge-smartthings.SmartThings",
                        "name": "SmartThings",  
                        "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
                        "app_id": "[redacted]",
                        "access_token": "[redacted]"
                }
        ]
}
