### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by deldrid1** [pdlove/homebridge-smartthings#49]
I'm getting an error when trying to run homebridge:

``` bash
$ homebridge
Loaded plugin: homebridge-smartthings
Registering platform 'homebridge-smartthings.SmartThings'

---
Loaded config.json with 0 accessories and 1 platforms.

---
Loading 1 platforms...
[SmartThings] Initializing SmartThings platform...
[SmartThings] Fetching Smart Things devices.
[SmartThings] Device Added - Group lights, Name GE Link Bulb, ID 7250950c-0619-45f1-8a62-125722bd7580
[SmartThings] Device Added - Group switch, Name Garage Door, ID 740a869e-36a4-4f67-a37c-8da3a0395e36
[SmartThings] Device Added - Group sensor, Name Austin's iPhone, ID a1229814-9927-4202-9328-51b5671569e5
[SmartThings] Device Added - Group sensor, Name Back Door, ID fa46ab73-5801-4d36-9d66-5b425b2dd1db
[SmartThings] Device Added - Group sensor, Name Dining Room, ID b91dcc0b-c0e3-43e1-8b39-77a8419d1665
[SmartThings] Device Added - Group sensor, Name Front Door, ID 6c3d585c-ebaa-4950-b351-5f6c6da7a6be
[SmartThings] Device Added - Group sensor, Name Jo's Room Window, ID 32a63eb2-b275-470e-8ff4-f61abe920caa
[SmartThings] Device Added - Group sensor, Name Living Room, ID 69a2247f-aef9-4586-968c-debdd0053d93
[SmartThings] Device Added - Group sensor, Name Magan's iPhone, ID f26ef7ef-3ec6-431a-8965-c471e6f12b08
[SmartThings] Device Added - Group sensor, Name Pink Room Window, ID 564acbca-dd70-4398-9c1f-33519ce7cdf9
[SmartThings] Device Added - Group sensor, Name Side Door, ID 10dbd066-bdda-4eb3-b3ae-814c81ee6d84
[SmartThings] Device Added - Group sensor, Name Upstairs Hallway, ID 4d655996-3786-4a6a-a53b-d142a0b40ee3
[SmartThings] Device Added - Group sensor, Name Garage, ID 84ae1c3a-96f7-4949-b98b-353a30e3c075
[SmartThings] Device Added - Group sensor, Name Garage Door, ID 50e67136-65b3-40ee-bebd-25131dcb1e0e
[SmartThings] Device Added - Group switch, Name Aeon Siren, ID 1731fa1f-a133-4411-b07e-b082e2e4d812
[SmartThings] Unknown Capabilities: ["Relay Switch","Alarm"]
[SmartThings] Initializing platform accessory 'GE Link Bulb'...
[SmartThings] Initializing platform accessory 'Garage Door'...
[SmartThings] Initializing platform accessory 'Austin's iPhone'...
[SmartThings] Initializing platform accessory 'Back Door'...
[SmartThings] Initializing platform accessory 'Dining Room'...
[SmartThings] Initializing platform accessory 'Front Door'...
[SmartThings] Initializing platform accessory 'Jo's Room Window'...
[SmartThings] Initializing platform accessory 'Living Room'...
[SmartThings] Initializing platform accessory 'Magan's iPhone'...
[SmartThings] Initializing platform accessory 'Pink Room Window'...
[SmartThings] Initializing platform accessory 'Side Door'...
[SmartThings] Initializing platform accessory 'Upstairs Hallway'...
[SmartThings] Initializing platform accessory 'Garage'...
[SmartThings] Initializing platform accessory 'Garage Door'...
/Users/AustinEldridge/.nvm/versions/node/v5.6.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:183
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: fbb0bc6a-7b17-479e-8910-a8b7da88f08b
    at Bridge.Accessory.addBridgedAccessory (/Users/AustinEldridge/.nvm/versions/node/v5.6.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:183:13)
    at Server.<anonymous> (/Users/AustinEldridge/.nvm/versions/node/v5.6.0/lib/node_modules/homebridge/lib/server.js:226:24)
    at /Users/AustinEldridge/.nvm/versions/node/v5.6.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /Users/AustinEldridge/.nvm/versions/node/v5.6.0/lib/node_modules/homebridge-smartthings/index.js:104:4
    at /Users/AustinEldridge/.nvm/versions/node/v5.6.0/lib/node_modules/homebridge-smartthings/index.js:81:5
    at /Users/AustinEldridge/.nvm/versions/node/v5.6.0/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:93:13
    at IncomingMessage.<anonymous> (/Users/AustinEldridge/.nvm/versions/node/v5.6.0/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:46:27)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
```

I can fix it by removing some of my devices but the README specifically states

> If you select the same device in multiple categories it will only be shown once in HomeKit, so you can safely check them all in all groups.

I've not had time to dig into it myself - any thoughts on what the issue is?

**Comment by pdlove** [comment]
That's really odd. I don't see any reason it should be doing that. Try removing "Garage Door" from the app and let me know if it works right. I do have one idea I'll be able to check later tonight

**Comment by deldrid1** [comment]
Unchecking "Garage Door" from my list of Sensor Devices gets homebridge working (well at least running on my laptop - I'm actually on the road and haven't been able to test with Smartthings).

**Comment by pdlove** [comment]
@deldrid1 Do you still have this problem?

**Comment by deldrid1** [comment]
Yes - I'm still having the issue if I have every device checked in the SmartApp.

I've upgraded to the latest version of the SmartApp, version 5.9.0 of node, version 0.4.7 of homebridge-smartthings, and version 0.3.2 of homebridge, 

```
$ homebridge
[3/28/2016, 1:01:33 PM] Loaded plugin: homebridge-http
[3/28/2016, 1:01:33 PM] Registering accessory 'homebridge-http.Http'
[3/28/2016, 1:01:33 PM] ---
[3/28/2016, 1:01:33 PM] Loaded plugin: homebridge-smartthings
[3/28/2016, 1:01:33 PM] Registering platform 'homebridge-smartthings.SmartThings'
[3/28/2016, 1:01:33 PM] ---
[3/28/2016, 1:01:33 PM] Loaded config.json with 0 accessories and 1 platforms.
[3/28/2016, 1:01:33 PM] ---
[3/28/2016, 1:01:33 PM] Loading 1 platforms...
[3/28/2016, 1:01:33 PM] [SmartThings] Initializing SmartThings platform...
[3/28/2016, 1:01:33 PM] [SmartThings] Fetching Smart Things devices.
[3/28/2016, 1:01:33 PM] Loading 0 accessories...
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group lights, Name GE Link Bulb, ID 7250950c-0619-45f1-8a62-125722bd7580
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group switch, Name Garage Door, ID 740a869e-36a4-4f67-a37c-8da3a0395e36
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group switch, Name Kodi (Eaton-GMBD-PI-1) Speaker, ID baa963d8-74f5-4f06-b3e7-5fa81df6efcf
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Austin's iPhone, ID a1229814-9927-4202-9328-51b5671569e5
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Back Door, ID fa46ab73-5801-4d36-9d66-5b425b2dd1db
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Dining Room, ID b91dcc0b-c0e3-43e1-8b39-77a8419d1665
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Front Door, ID 6c3d585c-ebaa-4950-b351-5f6c6da7a6be
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Garage, ID 84ae1c3a-96f7-4949-b98b-353a30e3c075
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Garage Door, ID 50e67136-65b3-40ee-bebd-25131dcb1e0e
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Jo's Room Window, ID 32a63eb2-b275-470e-8ff4-f61abe920caa
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Living Room, ID 69a2247f-aef9-4586-968c-debdd0053d93
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Magan's iPhone, ID f26ef7ef-3ec6-431a-8965-c471e6f12b08
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Pink Room Window, ID 564acbca-dd70-4398-9c1f-33519ce7cdf9
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Side Door, ID 10dbd066-bdda-4eb3-b3ae-814c81ee6d84
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group sensor, Name Upstairs Hallway, ID 4d655996-3786-4a6a-a53b-d142a0b40ee3
[3/28/2016, 1:01:34 PM] [SmartThings] Device Added - Group switch, Name Aeon Siren, ID 1731fa1f-a133-4411-b07e-b082e2e4d812
[3/28/2016, 1:01:34 PM] [SmartThings] Unknown Capabilities: ["Relay Switch","Music Player","Speech Synthesis","Alarm"]
[3/28/2016, 1:01:34 PM] [SmartThings] Initializing platform accessory 'GE Link Bulb'...
[3/28/2016, 1:01:34 PM] [SmartThings] Initializing platform accessory 'Garage Door'...
[3/28/2016, 1:01:34 PM] [SmartThings] Initializing platform accessory 'Kodi (Eaton-GMBD-PI-1) Speaker'...
[3/28/2016, 1:01:34 PM] [SmartThings] Initializing platform accessory 'Austin's iPhone'...
[3/28/2016, 1:01:34 PM] [SmartThings] Initializing platform accessory 'Back Door'...
[3/28/2016, 1:01:34 PM] [SmartThings] Initializing platform accessory 'Dining Room'...
[3/28/2016, 1:01:34 PM] [SmartThings] Initializing platform accessory 'Front Door'...
[3/28/2016, 1:01:34 PM] [SmartThings] Initializing platform accessory 'Garage'...
[3/28/2016, 1:01:34 PM] [SmartThings] Initializing platform accessory 'Garage Door'...
/Users/AustinEldridge/.nvm/versions/node/v5.9.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:217
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: fbb0bc6a-7b17-479e-8910-a8b7da88f08b
    at Bridge.Accessory.addBridgedAccessory (/Users/AustinEldridge/.nvm/versions/node/v5.9.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:217:13)
    at Server.<anonymous> (/Users/AustinEldridge/.nvm/versions/node/v5.9.0/lib/node_modules/homebridge/lib/server.js:347:24)
    at /Users/AustinEldridge/.nvm/versions/node/v5.9.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /Users/AustinEldridge/.nvm/versions/node/v5.9.0/lib/node_modules/homebridge-smartthings/index.js:107:4
    at /Users/AustinEldridge/.nvm/versions/node/v5.9.0/lib/node_modules/homebridge-smartthings/index.js:84:5
    at /Users/AustinEldridge/.nvm/versions/node/v5.9.0/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:95:29
    at IncomingMessage.<anonymous> (/Users/AustinEldridge/.nvm/versions/node/v5.9.0/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:46:29)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
```

**Comment by h00pak** [comment]
I upgraded  the SmarThings plug in today and now keep getting this message. I had to change my config.json to name SmarThings as -v2 to even get it to run now. Any ideas? I get the QR code and everything looks okay and then immediately blows up.

(node:7546) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 1ea96496-3cbf-4c8b-ab85-a0c1e0152857
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:414:15)
    at Bridge.Accessory._this.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:448:12)
    at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:528:17)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:316:10)
    at ST_Platform.addDevice (/usr/local/lib/node_modules/homebridge-smartthings/src/ST_Platform.js:183:25)
    at /usr/local/lib/node_modules/homebridge-smartthings/src/ST_Platform.js:154:61
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-smartthings/src/ST_Platform.js:154:38
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7546) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7546) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
