### ISSUE TITLE
Homebridge-Smartthings Error

### ISSUE THREAD

**Issue by mshah7** [pdlove/homebridge-smartthings#57]
nodejs -v
v0.6.19

"platform": "homebridge-smartthings.SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "xxxx",
            "access_token": "xxxx",
            "polling_seconds": 60,
            "update_seconds":1

I get the following error

[Sat Mar 12 2016 07:22:34 GMT+0000 (UTC)] ====================
[Sat Mar 12 2016 07:22:34 GMT+0000 (UTC)] ERROR LOADING PLUGIN homebridge-smartthings:
[Sat Mar 12 2016 07:22:34 GMT+0000 (UTC)] /usr/local/lib/node_modules/homebridge-smartthings/index.js:109
addAttributeUsage(attribute, deviceid, mycharacteristic) {
^
SyntaxError: Unexpected token (
at exports.runInThisContext (vm.js:73:16)
at Module._compile (module.js:443:25)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
at Server. (/usr/local/lib/node_modules/homebridge/lib/server.js:112:14)
at Array.forEach (native)
at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:108:22)
at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:43:24)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
[Sat Mar 12 2016 07:22:34 GMT+0000 (UTC)] ====================

**Comment by pdlove** [comment]
I haven't been able to get home bridge to work on any version of node prior to v4. Please upgrade. I did have issues getting my Raspberry pi to upgrade and have instructions if that is what you are using.

**Comment by mshah7** [comment]
tried to update node from v0.12 to v5.x
update did not succeed, still shows node v0.12, might have to start from scratch
do I need to also update Debian Wheezy to Jessie ?

**Comment by pdlove** [comment]
@mshah7 What hardware platform are you using?
