### ISSUE TITLE
Error at startup - dns service error: name conflict

### ISSUE THREAD

**Issue by Kevin1248** [pdlove/homebridge-smartthings#61]
Updated to all the latest homebridge repositories:

node -v   v5.3.0
npm view homebridge version  0.3.1
npm view homebridge-smartthings version  0.4.4
npm view hap-nodejs version  0.2.7

Get the following error at startup:

Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[3/16/2016, 9:30:33 PM] Homebridge is running on port 51827.
/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:498:20)
    at emitNone (events.js:67:13)
    at HAPServer.emit (events.js:166:7)
    at HAPServer._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:169:8)
    at emitNone (events.js:67:13)
    at EventedHTTPServer.emit (events.js:166:7)

**Comment by Kevin1248** [comment]
Never mind, I found the problem!  I had homebridge running automatically at reboot, and then I was attempting to start another one manually.
