### ISSUE TITLE
npm install -g homebridge installation error

### ISSUE THREAD

**Issue by xxKeoxx** [pdlove/homebridge-smartthings#69]
Running npm install -g homebridge on a VM running centos 7 generates a failure:

[npm-debug.txt](https://github.com/pdlove/homebridge-smartthings/files/284724/npm-debug.txt)

Any advice on how to resolve this?

```
> mdns@2.3.3 install /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.4.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/.node-gyp"
make: Entering directory `/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
                    ^
compilation terminated.
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory `/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-327.13.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.10.0-327.13.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

**Comment by aabrook** [comment]
I followed the comment here to get it installed:
https://github.com/npm/npm/issues/9298#issuecomment-131633308

**Comment by telsin** [comment]
on centos 7/rhel7, it needs avahi-compat-libdns_sd-devel, this will install it for you:

`sudo yum install -y avahi-compat-libdns_sd-devel`

**Comment by DrLongGhost** [comment]
I had the same issue on Ubuntu and as @aabrook said, installing the missing dependency via sudo apt-get install libavahi-compat-libdnssd-dev then deleting/reinstalling the half-installed package worked. Thanks!
