### ISSUE TITLE
Error after installing "homebridge-smartthings"

### ISSUE THREAD

**Issue by casper-gh** [pdlove/homebridge-smartthings#75]
Without `homebridge-smartthings`, I could launch homebridge and register it with home app iOS, however there is no device found after adding the accessory.

So I was thinking if it has anything to do with `homebridge-smartthings` installation. So if I install it, I got this error when running `homebridge`:

```
[6/19/2016, 2:55:16 AM] Loaded plugin: homebridge-legacy-plugins
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.AD2USB'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.Carwings'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.ELKM1'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.FileSensor'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.HomeMatic'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.HttpThermometer'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.Tesla'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.X10'
[6/19/2016, 2:55:16 AM] Registering accessory 'homebridge-legacy-plugins.mpdclient'
[6/19/2016, 2:55:16 AM] Registering platform 'homebridge-legacy-plugins.Domoticz'
[6/19/2016, 2:55:16 AM] Registering platform 'homebridge-legacy-plugins.HomeAssistant'
[6/19/2016, 2:55:16 AM] Registering platform 'homebridge-legacy-plugins.HomeSeer'
[6/19/2016, 2:55:16 AM] Registering platform 'homebridge-legacy-plugins.ISY'
[6/19/2016, 2:55:16 AM] Registering platform 'homebridge-legacy-plugins.LIFx'
[6/19/2016, 2:55:16 AM] Registering platform 'homebridge-legacy-plugins.SmartThings'
[6/19/2016, 2:55:16 AM] Registering platform 'homebridge-legacy-plugins.TelldusLive'
[6/19/2016, 2:55:16 AM] Registering platform 'homebridge-legacy-plugins.ZWayServer'
[6/19/2016, 2:55:16 AM] ---
[6/19/2016, 2:55:16 AM] Loaded plugin: homebridge-smartthings
[6/19/2016, 2:55:16 AM] Registering platform 'homebridge-smartthings.SmartThings'
[6/19/2016, 2:55:16 AM] ---
[6/19/2016, 2:55:16 AM] Loaded config.json with 0 accessories and 1 platforms.
[6/19/2016, 2:55:16 AM] ---
[6/19/2016, 2:55:16 AM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:103
      throw new Error("The requested platform '" + name + "' has been registered multiple times. Please be more specific by writing one of: " + found.join(", "));
      ^

Error: The requested platform 'SmartThings' has been registered multiple times. Please be more specific by writing one of: homebridge-legacy-plugins.SmartThings, homebridge-smartthings.SmartThings
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:103:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:263:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

```

**Comment by casper-gh** [comment]
Sorry I found the culprit, no conflict after deleting `homebridge-legacy-plugins`
