### ISSUE TITLE
New Issue Just started

### ISSUE THREAD

**Issue by flynhawaiian** [pdlove/homebridge-smartthings#83]
I have a new issue that just started a few days ago.  I've reinstalled the app and still have the same issue.

[7/29/2016, 12:02:05 PM] [SmartThings] Initializing homebridge-smartthings.SmartThings platform...
[7/29/2016, 12:02:05 PM] [SmartThings] Fetching Smart Things devices.
[7/29/2016, 12:02:06 PM] [SmartThings] Error received type undefined - undefined
[7/29/2016, 12:02:06 PM] [SmartThings] Unknown Capabilities: []

Any ideas what's going on?

**Comment by flynhawaiian** [comment]
I've updated the token and ID and still nothing.

**Comment by Wildcat1** [comment]
I am seeing the same issue and know this is also being tracked over at the Homebridge issues page (https://github.com/nfarina/homebridge/issues/725#issuecomment-236619577). Hoping we can get some resolution to this as it just started happening out of the blue. @pdlove have you seen this issue on your setup yet ? If so any ideas what might be causing this ?

Thanks as always

**Comment by Wildcat1** [comment]
@flynhawaiian I just posted what I just did with my instance over at the Homebridge issues page which has worked for me. Not sure if you are running on a Mac or not. If you are then try these steps I list below (sorry to double post here but thought would be easier than making people navigate). Let me know if this works for you:

I just resolved this for my instance of this on my Mac. First I went into the ~/.homebridge directory and in both accessories & persist subfolders, deleted CachedAccessories, AccessoryInfo & IdentifierCache. After this I went back into the SmartThings on iOS and removed all devices from the JSON Complete Api smart app. After this I re-added these which then generated the new access token and proceeded to update my JSON config file with this new token. I then reinstalled the plugins for the Mac and also removed Homebridge accessory from my iOS Homekit app of choice (Home by Matthias). After this ran Homebridge on the Mac, everything came up as expected without any issues or errors, re-added Homebridge as an accessory on iOS and all devices came back. Now onto the work of re-assigning to rooms and in configuration of scenes etc.

**Comment by flynhawaiian** [comment]
Now I’m getting something weird...

[8/1/2016, 9:57:03 PM] Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:155:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:480:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:92:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:82:10)

**Comment by flynhawaiian** [comment]
restarted and it went away.  Now it is only showing this..

[8/1/2016, 10:14:10 PM] Loaded plugin: homebridge-smartthings
[8/1/2016, 10:14:10 PM] Registering platform 'homebridge-smartthings.SmartThings'
[8/1/2016, 10:14:10 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[8/1/2016, 10:14:10 PM] Homebridge is running on port 51826.

But nothing is working...

**Comment by pdlove** [comment]
The address in use error indicates homebridge is already running. Reboot and try again.
I'm not having any issues myself.

**Comment by flynhawaiian** [comment]
Okay rebooted figured out that 2 instances were running.  Got that fixed.  Now the problem is:

[8/1/2016, 10:38:33 PM] Loaded plugin: homebridge-smartthings
[8/1/2016, 10:38:33 PM] Registering platform 'homebridge-smartthings.SmartThings'
[8/1/2016, 10:38:33 PM] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[8/1/2016, 10:38:33 PM] Homebridge is running on port 51826.

For some reason it is not registering the accessories as pointed out in the app on smart things.

**Comment by flynhawaiian** [comment]
Basically all i see under home is home bridge and nothing else is there or is registered.

**Comment by flynhawaiian** [comment]
I've deleted the install of both home bridge and homebridge-smartthings, reinstalled and nothing.  Not sure what the issue is.  Everything was working fine!

**Comment by flynhawaiian** [comment]
OKAY got it working again!!  WOOT

**Comment by jb901** [comment]
Same as flynhawaiian - not working for me at all..

[9/15/2016, 11:52:14 PM] [SmartThings] Initializing homebridge-smartthings.SmartThings platform...
[9/15/2016, 11:52:14 PM] [SmartThings] Fetching Smart Things devices.
[9/15/2016, 11:52:14 PM] [LiFx] Initializing LifxLan platform...
[9/15/2016, 11:52:14 PM] [LiFx] Server Listening...
[9/15/2016, 11:52:14 PM] [LiFx] Online: Kitchen table [d073d502b434]
[9/15/2016, 11:52:14 PM] [SmartThings] Error received type undefined - undefined
[9/15/2016, 11:52:14 PM] [SmartThings] Unknown Capabilities: []
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
```

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘
```

[9/15/2016, 11:52:14 PM] Homebridge is running on port 51826.
