### ISSUE TITLE
Home app on iOS sees Homebridge, but will not pair.

### ISSUE THREAD

**Issue by kevinwestby** [pdlove/homebridge-smartthings#94]
Just setting this up for first time....looks like it starts, then I get the following.  Home app on iOS sees Homebridge, but will not pair.  thoughts?

[9/16/2016, 3:46:54 PM] Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:155:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:480:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:92:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:351:14)

**Comment by kevinwestby** [comment]
I am running Homebridge on my Raspberry Pi

**Comment by kevinwestby** [comment]
Please disregard....I have resolved the issue

**Comment by petaren** [comment]
@kevinwestby how did you resolve this issue?

**Comment by pdlove** [comment]
For future reference, the error "Error: listen EADDRINUSE :::51826" generally means homebridge is already running, possibly from a prior crashed execution.

**Comment by kevinwestby** [comment]
Had to reset everything and start over

Kevin Westby, CISSP, CCSP, CIPT
(319) 795-0420
kevin@kevinwestby.com<mailto:kevin@kevinwestby.com>

________________________________
